config/routes.rb
RottenMangoes::Application.routes.draw do

  resources :movies do 
    resources :reviews, only: [:new, :create]
  end
  resources :actors
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  root to: 'movies#index'

  namespace :admin do
    resources :users
  end

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  has_many :roles
  has_many :movies, through: :roles
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :actors
  has_many :reviews
  mount_uploader :poster_image_url, ImageUploader

  validates :title,
    presence: true

  validates :director,
    presence: true

  validates :runtime_in_minutes,
    numericality: { only_integer: true }

  validates :description,
    presence: true

  validates :poster_image_url,
    presence: true

  validates :release_date,
    presence: true

  validate :release_date_is_in_the_past

  def review_average
    reviews.sum(:rating_out_of_ten)/((reviews.size).nonzero? || 1)
  end

  def self.search(query, duration)
    movies = Movie.all
    movies = movies.where("title LIKE ? OR director LIKE ?", "%#{query}%","%#{query}%" ) if !query.blank?
    
    case duration 
    when '1'
     movies = movies.where("runtime_in_minutes < 90")
    when '2'
     movies = movies.where("runtime_in_minutes > 90 AND runtime_in_minutes < 120 ")
    when '3'
     movies = movies.where("runtime_in_minutes > 120")
    end
    movies
  end

  protected

  def release_date_is_in_the_past
    if release_date.present? && release_date > Date.today
      errors.add(:release_date, "should probably be in the past")
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :user,
    presence: true

  validates :movie,
    presence: true

  validates :text,
    presence: true

  validates :rating_out_of_ten,
    numericality: { only_integer: true }
  validates :rating_out_of_ten,
    numericality: { greater_than_or_equal_to: 1 }
  validates :rating_out_of_ten,
    numericality: { less_than_or_equal_to: 10 }
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :movie
  belongs_to :actor
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews

  has_secure_password

  validates :email,
  presence: :true

  validates :firstname,
  presence: :true

  validates :lastname,
  presence: :true

  validates :password,
  length: {in: 6..20}, on: :create

  def full_name
    "#{firstname} #{lastname}"
  end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def index
    @actors = Actor.all
  end

  def show
    @actor = Actor.find(params[:id])
  end

  def new
    @actor = Actor.new
  end

  def edit
    @actor = Actor.find(params[:id])
  end

  def create
    @actor = Actor.new(actor_params)

    if @actor.save
      redirect_to actors_path, notice: "#{@actor.firstname} #{@actor.lastname} was submitted successfully!"
    else
      render :new
    end
  end

  def update 
    @actor = Actor.find(params[:id])
    if @actor.update_attributes(actor_params)
      redirect_to actor_path(@actor)
    else
      render :edit
    end
  end

  def destroy
    @actor = Actor.find(params[:id])
    @actor.destroy
    redirect_to actors_path
  end

  protected

  def actor_params
    params.require(:actor).permit(
      :firstname, :lastname
    )
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_filter :authorized?

  def index
    @users = User.all.page(params[:page]).per(5)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    UserMailer.deleted_email(@user).deliver_now
    redirect_to admin_users_path
  end

private

  def authorized?
    unless current_user && current_user.admin == true
      flash[:error] = "You are not authorized to view that page."
      redirect_to root_path
    end
  end
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected 

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    #if search, title is always true because blank is truthy 
    if params[:query] 
      @movies = Movie.search(params[:query],params[:duration]).order(title: :ASC)
    else
      @movies = Movie.all.order(title: :ASC)
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update 
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :poster_image_url, :description  
    )
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :restrict_access
  before_filter :load_movie

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end
  
  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil 
    redirect_to movies_path, notice: "Adios!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}"
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end

  def duration_options
    @options = 
    [
      ["---",0],
      ["Under 90 minutes",1],
      ["Between 90 and 120 minutes",2],
      ["Over 120 minutes",3]
    ]  
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/actors/_form.html.erb
<%= form_for @actor do |f| %>
  <% if @actor.errors.any? %>
    <div>
      <%= pluralize(@actor.errors.count, "error") %> prevented this actor from being submitted:
      <ul>
        <% @actor.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname%>
  </div>
  <div>
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname%>
  </div>
  <div>
    <%= f.submit "Submit" %> 
  </div>
<% end %>

app/views/actors/edit.html.erb
<%= link_to "Back to this actor", actor_path(@actor) %>

<h2>Edit this actor.</h2>
<%= render 'form' %>

app/views/actors/index.html.erb
<h1>Actors#index</h1>
<p>Find me in app/views/actors/index.html.erb</p>

app/views/actors/new.html.erb
<%= link_to "Back to all actors", actors_path %>

<h2>Submit an actor!</h2>
<%= render 'form' %>

app/views/actors/show.html.erb
<h1>Actors#show</h1>
<p>Find me in app/views/actors/show.html.erb</p>

app/views/admin/users/index.html.erb
<h1>Rotten Mangoes Admin Page</h1>

<%= paginate @users %>

<%= link_to "Back to movies!", movies_path %>
<hr>
<% @users.each do |user| %>
  <h2><%= user.full_name %></h2>
  <h3><%= user.email %></h3>
  <%= link_to "delete", admin_user_path(user), method: :delete, data: {confirm: "You sure?"} %>
<hr>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
        <% if current_user.admin == true %>
          <%= link_to "Admin Page", admin_users_path %>
        <% end %> 
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </small>
  <small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>  
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, :html => {:multipart => true} do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :release_date %><br>
    <%= f.date_field :release_date %>
  </div>
  <div>
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div>
    <%= f.label :runtime_in_minutes %><br>
    <%= f.number_field :runtime_in_minutes %>
  </div>
  <div>
    <%= f.label :poster_image %><br>
    <%= f.file_field :poster_image_url %>
  </div>
  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.submit "Submit" %> 
  </div>
<% end %>

app/views/movies/_movie.html.erb
  <%= image_tag(movie.poster_image_url_url(:thumb).to_s)%>
  <h2><%= link_to movie.title, movie_path(movie) %></h2> <%= movie.review_average %>/10
  <h3><%= formatted_date(movie.release_date) %></h3>
  <h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes </h4>
  <p><%= movie.description %></p>
  <hr>

app/views/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>

<h2>Edit this movie.</h2>
<%= render 'form' %>

app/views/movies/index.html.erb
<h1>Rotten Mangoes</h1>

<%= link_to "Submit a movie!", new_movie_path %>
<%= form_tag movies_path, method: "get" do %>
  <p>
  <%= text_field_tag :query, "", placeholder: "Search by Title or Director" %>
  <%= select_tag "duration", options_for_select(duration_options)%>
  <%= submit_tag "search", :name => nil %>
  </p>
<% end %>

<hr>
<% @movies.each do |movie| %>
  <%= render partial: 'movie', object: movie %>
<% end %>

app/views/movies/new.html.erb
<%= link_to "Back to all movies", movies_path %>

<h2>Submit a movie!</h2>
<%= render 'form' %>

app/views/movies/show.html.erb
<%= link_to "Back to all movies", movies_path %><br/>

<%= image_tag(@movie.poster_image_url_url.to_s)%>
<h2><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, confirm: "You sure?" %>)</h2>
<h3><%= formatted_date(@movie.release_date) %></h3>
<h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
<p><%= @movie.description %></p>

<hr>

<h3>Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <small>- <%= review.user.full_name %></small><br/>
  <% end %>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>
<h2>Write a review of <em><%= @movie.title %></em>.</h2>
<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div>
  <%= f.label :text %><br>
  <%= f.text_area "text" %>
</div>
<div>
  <%= f.label :rating_out_of_ten %><br>
  <%= f.number_field :rating_out_of_ten %>
</div>
<div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div>
          <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div>
        <%= f.label :email %><br>
        <%= f.text_field :email %>
      </div>
      <div>
        <%= f.label :firstname, "First Name" %><br>
        <%= f.text_field :firstname %>
      </div>
      <div>
        <%= f.label :lastname, "Last Name" %><br>
        <%= f.text_field :lastname %>
      </div>
      <div>
        <%= f.label :password %><br>
        <%= f.password_field :password %>
      </div>
      <div>
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation %>
      </div>
      <div><%= f.submit "Submit" %></div>
    <% end %>